# Generated by Django 4.1.5 on 2023-01-25 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gave_like',
            field=models.ManyToManyField(related_name='posts_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
