# Generated by Django 4.1.5 on 2023-01-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_gave_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='gave_like',
            new_name='users_gave_like',
        ),
    ]
