# Generated by Django 4.1.5 on 2023-01-29 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_gave_like_post_users_gave_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_others',
            field=models.ManyToManyField(related_name='follow_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='users_gave_like',
            field=models.ManyToManyField(null=True, related_name='posts_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
