# Generated by Django 4.1.5 on 2023-01-29 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_follow_others_alter_post_users_gave_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='follow_others',
            field=models.ManyToManyField(null=True, related_name='follow_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
